colorscheme material
set list
set listchars=eol:↴
set signcolumn=yes
set hidden
set autoindent
set wildmode=list:longest,full
set ruler
set noswapfile
set list
set hidden
set nohlsearch
set modeline
set relativenumber
set number
set cursorline
set inccommand=nosplit
set incsearch
set cmdheight=1
set updatetime=1000
set splitright
set termguicolors
set timeoutlen=750
set foldlevel=4
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
