" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'lervag/vim-latex'
Plugin 'kchmck/vim-coffee-script'
Plugin 'pangloss/vim-javascript'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'github-theme'
Plugin 'luochen1990/rainbow'
Plugin 'flazz/vim-colorschemes'

call vundle#end()

filetype plugin indent on
syntax enable
set omnifunc=syntaxcomplete#Complete
set background=dark
colorscheme solarized
set number
set ruler
set showcmd
set nobackup
set noswapfile
set list
set hidden
set tabstop=4
set shiftwidth=4
set expandtab

" fast out of insert mode
inoremap ii <Esc> 

" misc mappings
cmap w!! w !sudo tee % >/dev/null
nnoremap ,h <C-w>h
nnoremap ,j <C-w>j
nnoremap ,k <C-w>k
nnoremap ,l <C-w>l 
nnoremap ; :
nnoremap '' <Esc>:w<Enter>
inoremap '' <Esc>:w<Enter>
nnoremap ,q :q<Enter>
nnoremap <C-e> A
nnoremap <C-a> I
nnoremap ,so :so $MYVIMRC<CR>
nnoremap ,ev :e $MYVIMRC<CR>
set virtualedit=all
set wildmenu
set hidden

" clipboard setting
execute "set <M-x>=\ex"
execute "set <M-v>=\ev"
execute "set <M-c>=\ec"
vnoremap <M-c> "+y
vnoremap <M-x> "+x
nnoremap <M-v> "+P
vnoremap <M-v> "+P
inoremap <M-v> <Esc>"+Pa

" for writing sip papers
nnoremap ,it <Esc>bi\textit{<Esc>ea}<Esc>
inoremap ,it <Esc>bi\textit{<Esc>ea}
inoremap ,oo OTU
inoremap ,cc $^{13}$C
nnoremap ,cc i$^{13}$C<Esc>
inoremap ,rr \ref{

" coffeescript settings
autocmd BufNewFile,BufReadPost *.coffee setl shiftwidth=2 expandtab
autocmd BufNewFile,BufReadPost *.coffee set tabstop=2
autocmd BufNewFile,BufReadPost *.coffee setl foldmethod=indent
autocmd BufNewFile,BufReadPost *.coffee nnoremap ,m :make -b<Enter>
autocmd BufNewFile,BufReadPost *.coffee vnoremap C :'<,'>CoffeeCompile<Enter>
let coffee_make_options = '--bare'
let coffee_indent_keep_current = 1
setl scrollbind

" UltiSnips config
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="horizontal"

" vim-latex settings
let g:latex_complete_recursive_bib = 1
let g:tex_flavor="latex"
au BufRead *.tex setlocal spell  

" rainbow parentheses settings
let g:rainbow_conf = {
    \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
    \   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
    \   'operators': '_,_',
    \   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
    \   'separately': {
    \       '*': {},
    \       'tex': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
    \       },
    \       'lisp': {
    \           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
    \       },
    \       'vim': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
    \       },
    \       'html': {
    \           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
    \       },
    \       'css': 0,
    \   }
    \}
