" vimrc

" Vundle {{{
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'kchmck/vim-coffee-script'
Plugin 'LaTeX-Box-Team/LaTeX-Box'
Plugin 'pangloss/vim-javascript'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'github-theme'
Plugin 'tpope/vim-sensible' 
Plugin 'flazz/vim-colorschemes'
Plugin 'L9'
Plugin 'FuzzyFinder'
Plugin 'jacekd/vim-iawriter' 
Plugin 'mikewest/vimroom'
Plugin 'Reedes/vim-pencil'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'sjl/gundo.vim'

call vundle#end()
" }}}

" Settings {{{
filetype plugin indent on
syntax enable
set omnifunc=syntaxcomplete#Complete
set background=dark
colorscheme solarized
set number
set ruler
set showcmd
set nobackup
set noswapfile
set list
set hidden
set showcmd
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set virtualedit=all
set wildmenu
set hlsearch
let mapleader=","
set scrolloff=999
set cursorline
set showmatch
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set modelines=1
" }}}

" Mappings  {{{
" misc {{{
inoremap ii <Esc>
cmap w!! w !sudo tee % >/dev/null
nnoremap ,h <C-w>h
nnoremap ,j <C-w>j
nnoremap ,k <C-w>k
nnoremap ,l <C-w>l 
nnoremap j gj
nnoremap k gk
nnoremap gV `[v`]
noremap '' <Esc>:w<CR>
nnoremap ,q :q<CR>;sldkfa;sldaj;lfdks
nnoremap <C-e> A
nnoremap <C-a> I
nnoremap ,so :so $MYVIMRC<CR>
nnoremap ,ev :e $MYVIMRC<CR>
nnoremap <Leader>sc:let &scrolloff=999-&scrolloff<CR>
inoremap <Tab> <C-v><C-f>
nnoremap <Leader><space> :nohlsearch<CR>
nnoremap <Leader>u :GundoToggle<CR>
" }}}

" clipboard setting {{{
execute "set <M-x>=\ex"
execute "set <M-v>=\ev"
execute "set <M-c>=\ec"
vnoremap <M-c> "+y
vnoremap <M-x> "+x
nnoremap <M-v> "+P
vnoremap <M-v> "+P
inoremap <M-v> <Esc>"+Pa
" }}}

" for writing sip papers {{{
nnoremap ,it <Esc>bi\textit{<Esc>ea}<Esc>
inoremap ,it <Esc>bi\textit{<Esc>ea}
inoremap ,oo OTU
inoremap ,cc $^{13}$C
nnoremap ,cc i$^{13}$C<Esc>
inoremap ,rr \ref{
" }}}
" }}}

" plugin settings {{{
" latex-box {{{
let g:LatexBox_latexmk_options =
          \ '-pdflatex="pdflatex -synctex=1 %O %S"'
let g:LatexBox_Folding=1
function! EvinceSearch ()
    execute "silent !evince_forward_search " . LatexBox_GetOutputFile() . ' ' . line(".") . ' ' . '%:p'
    execute ':redraw!'
endfun
nmap ,ls :call EvinceSearch()<CR>
let g:LatexBox_latexmk_preview_continuously=1
let g:LatexBox_latexmk_options="-synctex=1"
let g:LatexBox_output_type="pdf" 
let g:LatexBox_viewer="evince" 
let g:LatexBox_quickfix=1 
let b:main_tex_file="full_paper.tex"
au FileType tex setl spell
au FileType tex colorscheme iawriter
au FileType tex setl linespace=10
au FileType tex setl formatoptions+=a
au FileType tex setl background=light
au FileType tex setl guifont=Cousine:h12
au FileType tex setl cole=2
au FileType tex setl foldlevelstart=1
let g:tex_flavor="latex"
" }}}

" coffeescript settings {{{
autocmd FileType coffee setl shiftwidth=2 expandtab
autocmd FileType coffee setl tabstop=2  smarttab
autocmd FileType coffee setl foldmethod=indent
autocmd FileType coffee nnoremap ,m :make -b<CR>
" autocmd BufWritePost *.coffee silent make -b!
let coffee_make_options = '--bare'
autocmd FileType coffee vnoremap C :'<,'>CoffeeCompile<CR>
let coffee_watch_vert = 1
let coffee_make_options = '--bare'
let coffee_indent_keep_current = 1
setl scrollbind
" }}}

" UltiSnips config {{{
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="horizontal"

if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif
" }}}
"}}}

" vim:foldmethod=marker:foldlevel=0
