# open the file manager
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Dotfiles 🗂️"
path = "~/dotfiles"
windows = ["editor", "claude-code", "quarto-preview"]

[[session]]
name = "Data730 📓"
path = "~/working/data730-lecture-notebooks/"
windows = ["pixi-jupyter"]

[[session]]
name = "Blog 🪵"
path = "~/working/chuckpr.github.io-worktree/"

[[session]]
name = "Active learning 🧬"
path = "~/working/lifeedit-ai-notebooks-worktree/activelearning-loop/ai_activelearning-loop/"

[[window]]
name = "pixi-jupyter"
startup_script = "pixi run jupyter lab --no-browser --ip '*'"

[[window]]
name = "editor"
startup_script = "nvim -c 'lua Snacks.picker.git_files()'"

[[window]]
name = "claude-code"
startup_script = "claude code"

[[window]]
name = "quarto-preview"
startup_script = "quarto preview docs/"
